add Android.mk for Android 9.0
For Android 10.0 and later, ethtool can be supported by default.
For Android 9.0, it is necessary to add Android.mk when porting ethtool.

This Android.mk is based on the following link:
Add Ethtool in Android
https://www.programmersought.com/article/53248957348/

To fix some compilation error, I add some configuration options to LOCAL_CFLAGS.
error: implicit declaration of function 'test_exit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
...
LOCAL_CFLAGS += -Wno-unused-parameter \
                -Wno-sign-compare \
                -Wno-sometimes-uninitialized \
                -Wno-missing-field-initializers \
                -Wno-pointer-arith \
                -Wno-unused-const-variable
error: use of undeclared identifier 'ethtool'
	PACKAGE " version " VERSION
LOCAL_CFLAGS += -DPACKAGE=\"ethtool\" \
                -DVERSION=\"5.4\"

Signed-off-by: Yongbo Zhang <yongbo.zhang.xh@renesas.com>